#!/usr/bin/env python3
"""Pre-render the criteria into index.html.

The cards are built client-side by assets/app.js, which means a crawler, link
preview, or any fetcher that does not run JavaScript sees an empty page. This
writes a static, semantic version of every criterion between the markers in
index.html so the content exists in the served HTML. app.js replaces it on boot,
so the interactive version is unaffected.

The static version is deliberately simpler than a rendered card: name, proposer,
threshold, score, status and the primary source. It exists to be read and
indexed, not to duplicate the card layout, which keeps the two from drifting.

Run before committing:  python3 build.py
"""

import html
import json
import re
import sys

DATA = 'data/definitions.json'
PAGE = 'index.html'
START = '<!-- prerender:start -->'
END = '<!-- prerender:end -->'

STATUS = {
    'passed': 'Met',
    'nearly': 'Nearly met',
    'in-progress': 'In progress',
    'early': 'Early',
    'failed': 'Deadline missed',
    'unfalsifiable': 'Unscoreable',
}


def esc(s):
    return html.escape(str(s if s is not None else ''), quote=True)


def strip_markup(s):
    """Card prose allows <strong>/<em>; the static summary takes neither."""
    return re.sub(r'<[^>]+>', '', str(s or ''))


def first_sentence(s, limit=260):
    text = ' '.join(strip_markup(s).split())
    if len(text) <= limit:
        return text
    cut = text[:limit]
    stop = cut.rfind('. ')
    return (cut[:stop + 1] if stop > 80 else cut.rstrip() + '…')


def render(d):
    score = '—' if d.get('status') == 'unfalsifiable' else '%s%%' % d.get('progress', 0)
    estimated = ' (editorial estimate)' if d.get('estimated') else ''
    who = ' · '.join(x for x in (d.get('proposer'), d.get('affiliation'),
                                 str(d['year']) if d.get('year') else None) if x)

    out = ['<article class="card" id="%s">' % esc(d['slug']),
           '<h3>%s</h3>' % esc(d.get('name')),
           '<p class="card-meta">%s</p>' % esc(who),
           '<p class="progress-row"><span class="progress-pct">%s</span> '
           '<span class="progress-caption">%s%s</span></p>'
           % (esc(score), esc(d.get('progress_note', 'toward stated threshold')), estimated),
           '<p><strong>%s.</strong> %s</p>'
           % (esc(STATUS.get(d.get('status'), 'Early')), esc(first_sentence(d.get('status_today'))))]

    if d.get('quote'):
        out.append('<blockquote class="quote">%s%s</blockquote>'
                   % (esc('“%s”' % d['quote']),
                      '<cite>%s</cite>' % esc(d['quote_source']) if d.get('quote_source') else ''))

    if d.get('measured'):
        out.append('<p class="measured">measured %s</p>' % esc(d['measured']))

    if d.get('source_url'):
        out.append('<p class="card-foot"><a href="%s" rel="noopener">Primary source</a></p>'
                   % esc(d['source_url']))

    out.append('</article>')
    return '\n'.join(out)


def main():
    data = json.loads(open(DATA, encoding='utf-8').read())
    defs = data['definitions']
    stated = [d for d in defs if d.get('claim') != 'proxy']
    proxies = [d for d in defs if d.get('claim') == 'proxy']

    block = [
        START,
        '<!-- Generated by build.py. Do not edit by hand; edit data/definitions.json. -->',
        '<div class="prerender">',
    ]
    # The stated heading already sits above this block in index.html.
    block += [render(d) for d in stated]
    if proxies:
        block.append('<h3 class="prerender-head">Milestones, not finish lines</h3>')
        block += [render(d) for d in proxies]
    block += ['</div>', END]

    page = open(PAGE, encoding='utf-8').read()
    if START not in page or END not in page:
        sys.exit('markers %s / %s not found in %s' % (START, END, PAGE))

    page = re.sub(re.escape(START) + '.*?' + re.escape(END),
                  lambda _: '\n'.join(block), page, flags=re.S)
    open(PAGE, 'w', encoding='utf-8').write(page)

    print('pre-rendered %d stated + %d proxy criteria into %s' % (len(stated), len(proxies), PAGE))


if __name__ == '__main__':
    main()
