#!/usr/bin/env python3
"""Pre-render the criteria into index.html.

The cards are built client-side by assets/app.js, which means a crawler, link
preview, or any fetcher that does not run JavaScript sees an empty page. This
writes a static, semantic version of every criterion between the markers in
index.html so the content exists in the served HTML. app.js replaces it on boot,
so the interactive version is unaffected.

The static version is deliberately simpler than a rendered card: name, proposer,
threshold, score, status and the primary source. It exists to be read and
indexed, not to duplicate the card layout, which keeps the two from drifting.

Run before committing:  python3 build.py
"""

import html
import json
import re
import sys

DATA = 'data/definitions.json'
PAGE = 'index.html'
START = '<!-- prerender:start -->'
END = '<!-- prerender:end -->'
PROXY_START = '<!-- prerender-proxies:start -->'
PROXY_END = '<!-- prerender-proxies:end -->'

STATUS = {
    'passed': 'Met',
    'nearly': 'Nearly met',
    'in-progress': 'In progress',
    'early': 'Early',
    'failed': 'Deadline missed',
    'unfalsifiable': 'Unscoreable',
}


def esc(s):
    return html.escape(str(s if s is not None else ''), quote=True)


def strip_markup(s):
    """Card prose allows <strong>/<em>; the static summary takes neither."""
    return re.sub(r'<[^>]+>', '', str(s or ''))


def first_sentence(s, limit=260):
    text = ' '.join(strip_markup(s).split())
    if len(text) <= limit:
        return text
    cut = text[:limit]
    stop = cut.rfind('. ')
    return (cut[:stop + 1] if stop > 80 else cut.rstrip() + '…')


def render(d):
    score = '—' if d.get('status') == 'unfalsifiable' else '%s%%' % d.get('progress', 0)
    estimated = ' (editorial estimate)' if d.get('estimated') else ''
    # Match app.js, which overrides the caption for a void criterion rather
    # than printing the authored progress_note.
    caption = ('no measurable threshold' if d.get('status') == 'unfalsifiable'
               else (d.get('progress_note') or 'toward stated threshold'))
    who = ' · '.join(x for x in (d.get('proposer'), d.get('affiliation'),
                                 str(d['year']) if d.get('year') else None) if x)

    out = ['<article class="card" id="%s">' % esc(d['slug']),
           '<h3>%s</h3>' % esc(d.get('name')),
           '<p class="card-meta">%s</p>' % esc(who),
           '<p class="progress-row"><span class="progress-pct">%s</span> '
           '<span class="progress-caption">%s%s</span></p>'
           % (esc(score), esc(caption), estimated),
           '<p><strong>%s.</strong> %s</p>'
           % (esc(STATUS.get(d.get('status'), 'Early')), esc(first_sentence(d.get('status_today'))))]

    if d.get('quote'):
        out.append('<blockquote class="quote">%s%s</blockquote>'
                   % (esc('“%s”' % d['quote']),
                      '<cite>%s</cite>' % esc(d['quote_source']) if d.get('quote_source') else ''))

    if d.get('measured'):
        out.append('<p class="measured">measured %s</p>' % esc(d['measured']))

    if d.get('source_url'):
        out.append('<p class="card-foot"><a href="%s" rel="noopener">Primary source</a></p>'
                   % esc(d['source_url']))

    out.append('</article>')
    return '\n'.join(out)


def main():
    data = json.loads(open(DATA, encoding='utf-8').read())
    defs = data['definitions']
    stated = [d for d in defs if d.get('claim') != 'proxy']
    proxies = [d for d in defs if d.get('claim') == 'proxy']

    GENERATED = '<!-- Generated by build.py. Do not edit by hand; edit data/definitions.json. -->'

    # Two blocks, each written into its own container. Filing the proxies inside
    # #cards would put them under the "stated definitions" heading for exactly
    # the readers the prerender exists for, inverting the site's main distinction.
    stated_block = [START, GENERATED, '<div class="prerender">'] + \
                   [render(d) for d in stated] + ['</div>', END]
    proxy_block = [PROXY_START, GENERATED, '<div class="prerender">'] + \
                  [render(d) for d in proxies] + ['</div>', PROXY_END]

    page = open(PAGE, encoding='utf-8').read()
    for a, b, name in ((START, END, 'stated'), (PROXY_START, PROXY_END, 'proxies')):
        if a not in page or b not in page:
            sys.exit('markers for %s (%s / %s) not found in %s' % (name, a, b, PAGE))

    for a, b, blk in ((START, END, stated_block), (PROXY_START, PROXY_END, proxy_block)):
        page = re.sub(re.escape(a) + '.*?' + re.escape(b),
                      lambda _, blk=blk: '\n'.join(blk), page, flags=re.S)
    open(PAGE, 'w', encoding='utf-8').write(page)

    print('pre-rendered %d stated + %d proxy criteria into %s' % (len(stated), len(proxies), PAGE))


if __name__ == '__main__':
    main()
